# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cprobert-s3sync 1.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "cprobert-s3sync"
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["cprobert"]
  s.date = "2013-10-28"
  s.email = "cprobert@gmail.com"
  s.executables = ["s3sync", "s3cmd"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/s3cmd",
    "bin/s3sync",
    "cprobert-s3sync.gemspec",
    "docs/README.txt",
    "docs/README_s3cmd.txt",
    "docs/s3config.yml.example",
    "lib/s3sync.rb",
    "lib/s3sync/HTTPStreaming.rb",
    "lib/s3sync/S3.rb",
    "lib/s3sync/S3_s3sync_mod.rb",
    "lib/s3sync/S3encoder.rb",
    "lib/s3sync/s3config.rb",
    "lib/s3sync/s3try.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "test/test_helper.rb",
    "test/test_s3sync.rb"
  ]
  s.homepage = "https://github.com/cprobert/s3sync"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.10"
  s.summary = "Fork of s3sync to be compatible with ruby 1.9.3"
end

